### ISSUE TITLE
How to predict a single image?

### ISSUE THREAD

**Issue by x12901** [dhkdnduq/PatchCore_anomaly_detection#6]
Error is reported when there is only one image in the folder.  
```
C:\ProgramData\Anaconda3\envs\PatchCore_anomaly_detection-main\python.exe D:/PatchCore_anomaly_detection-main/train.py
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
C:\ProgramData\Anaconda3\envs\PatchCore_anomaly_detection-main\lib\site-packages\torchvision\transforms\transforms.py:280: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  warnings.warn(
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2]
Traceback (most recent call last):
  File "D:/PatchCore_anomaly_detection-main/train.py", line 520, in <module>
    trainer.test(model)
  File "C:\ProgramData\Anaconda3\envs\PatchCore_anomaly_detection-main\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 579, in test
    results = self._run(model)
  File "C:\ProgramData\Anaconda3\envs\PatchCore_anomaly_detection-main\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 756, in _run
    self.dispatch()
  File "C:\ProgramData\Anaconda3\envs\PatchCore_anomaly_detection-main\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 793, in dispatch
    self.accelerator.start_evaluating(self)
  File "C:\ProgramData\Anaconda3\envs\PatchCore_anomaly_detection-main\lib\site-packages\pytorch_lightning\accelerators\accelerator.py", line 99, in start_evaluating
    self.training_type_plugin.start_evaluating(trainer)
  File "C:\ProgramData\Anaconda3\envs\PatchCore_anomaly_detection-main\lib\site-packages\pytorch_lightning\plugins\training_type\training_type_plugin.py", line 148, in start_evaluating
    self._results = trainer.run_stage()
  File "C:\ProgramData\Anaconda3\envs\PatchCore_anomaly_detection-main\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 804, in run_stage
    return self.run_evaluate()
  File "C:\ProgramData\Anaconda3\envs\PatchCore_anomaly_detection-main\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1044, in run_evaluate
    eval_loop_results = self.run_evaluation()
  File "C:\ProgramData\Anaconda3\envs\PatchCore_anomaly_detection-main\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 920, in run_evaluation
    dataloaders, max_batches = self.evaluation_loop.get_evaluation_dataloaders()
  File "C:\ProgramData\Anaconda3\envs\PatchCore_anomaly_detection-main\lib\site-packages\pytorch_lightning\trainer\evaluation_loop.py", line 56, in get_evaluation_dataloaders
    self.trainer.reset_test_dataloader(model)
  File "C:\ProgramData\Anaconda3\envs\PatchCore_anomaly_detection-main\lib\site-packages\pytorch_lightning\trainer\data_loading.py", line 420, in reset_test_dataloader
    self.num_test_batches, self.test_dataloaders = self._reset_eval_dataloader(model, 'test')
  File "C:\ProgramData\Anaconda3\envs\PatchCore_anomaly_detection-main\lib\site-packages\pytorch_lightning\trainer\data_loading.py", line 370, in _reset_eval_dataloader
    num_batches = len(dataloader) if has_len(dataloader) else float('inf')
  File "C:\ProgramData\Anaconda3\envs\PatchCore_anomaly_detection-main\lib\site-packages\pytorch_lightning\utilities\data.py", line 33, in has_len
    raise ValueError('`Dataloader` returned 0 length. Please make sure that it returns at least 1 batch')
ValueError: `Dataloader` returned 0 length. Please make sure that it returns at least 1 batch
```

**Comment by dhkdnduq** [comment]
Are you using the train mode?
Test mode should be used.
If you are using train mode,
Pickle size is produced very small , can't use it.
